### ISSUE TITLE
Arduino NES controller circuit URL dead

### ISSUE THREAD

**Issue by SieniWAT** [MicroGenesis5/Serial-NES-Controller#1]
Hi! Not sure if you are online anymore but I was interested in this project but unfortunately the URL you link to in the README is dead:
https://www.microgenesis5.com/_txt/nes.html

The link is also not on the wayback machine.

I'd really appreciate it if this page could be archived or brought back in some way. Thanks!

**Comment by MicroGenesis5** [comment]
SienWAT,

Thank you for the heads up, I updated the links. Here it is: [https://falconreach.net/_txt/nes.html](https://falconreach.net/_txt/nes.html)

Take care!

**Comment by SieniWAT** [comment]
Great, thanks!
